### ISSUE TITLE
Base Ruleset

### ISSUE THREAD

**Issue by fooman** [extdn/extdn-phpcs#13]
Working with Magento 2 there are currently 4 standards in use

[PSR-2](https://www.php-fig.org/psr/psr-2/) 
[MEQP2](https://github.com/magento/marketplace-eqp/tree/master/MEQP2)
[ECG2](https://github.com/magento-ecg/coding-standard/tree/master/EcgM2)
[Tests included in codebase](https://github.com/magento/magento2/blob/2.2-develop/dev/tests/static/framework/Magento/ruleset.xml)  

Let's assess the merits and choose one as the base ruleset.

**Comment by jissereitsma** [comment]
Correct. In the `ruleset.xml`, we can include other rulesets, like this: https://github.com/extdn/extdn-phpcs/blob/5b95af12c253572c593749b2525c2f99d543abe9/Extdn/ruleset.xml#L5

My idea was to create a composer dependency with both MEQP2 and ECG2 and then refer to them from within the `ruleset.xml` using a relative path (based upon the `vendor/`) folder. This seems how numerous others are doing it as well.

**Comment by schmengler** [comment]
I'll start collecting a minimal ruleset from those which should not be questionable to begin with, then open up others for discussion here.

**Comment by shochdoerfer** [comment]
You might also want to check out [deptrac](https://github.com/sensiolabs-de/deptrac) to check for architectural constraints.

**Comment by schmengler** [comment]
@shochdoerfer that looks great as an additional tool and I'll keep it in mind. Mid-term we want to offer a thorough toolset for extension quality checks, since many suggested rules can already not be implemented as phpcs sniffs. For now, we start by focussing on what's possible with phpcs

**Comment by schmengler** [comment]
@fooman as discussed, we will integrate the EQP2 ruleset on a per rule base with added documentation
