### ISSUE TITLE
Use coding standard for extdn-phpcs itself

### ISSUE THREAD

**Issue by schmengler** [extdn/extdn-phpcs#21]
I'll implement PSR-1 and PSR-2 checks and some static analysis for this repository. Should we add more?

**Comment by jissereitsma** [comment]
I think PSR standards are enough for the PHPCS classes in this repo.

**Comment by schmengler** [comment]
I started with the standards of PHP_CodeSniffer itself but stripped it down to PSR-1 and PSR-2 now:

https://github.com/extdn/extdn-phpcs/blob/ccf092ee8c5ec5193ea5a4bb649be11fc7632426/phpcs.xml.dist#L21-L22
