### ISSUE TITLE
Document "strict types" rule

### ISSUE THREAD

**Issue by schmengler** [extdn/extdn-phpcs#47]
The rule "Always declare strict types" (#6) still needs to be documented. Add documentation based on the rule documentation template.

**Comment by jissereitsma** [comment]
FYI: I'm currently working on a rule to implement this check.

**Comment by schmengler** [comment]
@jissereitsma rule is already implemented (PR #25), but misses documentation

**Comment by jissereitsma** [comment]
I'm not sure what I said 12 days ago, but I wanted to say I wanted to write this doc.

**Comment by schmengler** [comment]
Thanks :)
