### ISSUE TITLE
Travis fails with OpenSSL key generation error

### ISSUE THREAD

**Issue by jissereitsma** [extdn/extdn-phpcs#50]
Travis fails with an error on the command `openssl aes-256-cbc -K $encrypted_2b7e0505597a_key -iv $encrypted_2b7e0505597a_iv -in .travis/deploy_rsa_encrypted -out ~/.ssh/id_rsa -d` which is defined in the `travis.yml` file of this repository. Before jumping ahead to fix this, I would like to know why this is needed :)

**Comment by fooman** [comment]
My guess would be that this creates a private key used for accessing a github during composer install to not run into the github api limit for unauthenticated access. Not sure why travis fails in this instance - maybe only @schmengler can change it since he was the one that added it?

**Comment by fooman** [comment]
I am guessing it's this https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions - a PR can't access encrypted values. I have added your account as admin to the repo which should be a workaround.

@schmengler any chance we can achieve the same outcome without the encrypted key?

**Comment by schmengler** [comment]
@fooman this seems to be the issue. The command indeed decrypts a private key stored in Travis for unrestricted SSH access to Github.

I can try to generate one instead and see what Github has to say about keys that are not associated to any account or repository

**Comment by schmengler** [comment]
It doesn't fail ... yet. Let's keep it like that for now and see if we run into rate limits again.
