### ISSUE TITLE
Rule: Declare strict types

### ISSUE THREAD

**Issue by jissereitsma** [extdn/extdn-phpcs#6]
PHP scripts are encouraged to declare strict typing (`declare(strict_types=1)`).

**Comment by jissereitsma** [comment]
Small comment on this: Since this feature is there from PHP 7.0 onwards and since PHP 7.1 is the new requirement for Magento 2.3, this seems like a reasonable thing to do.

**Comment by navarr** [comment]
I also believe with M 2.3 Magento is internally requiring strict types be used

**Comment by larsroettig** [comment]
Hi @jissereitsma,I will work on it

**Comment by larsroettig** [comment]
@schmengler can be close is already done

**Comment by schmengler** [comment]
OK, I created a separate issue for the missing documentation

**Comment by buskamuza** [comment]
For Magento 2.3, it's not only internal rule, it's in Magento guidelines. See https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html#1-basic-programming-principles . Just for new code, as usual.
