### ISSUE TITLE
MEQP Update to version 4

### ISSUE THREAD

**Issue by milindsingh1** [extdn/extdn-phpcs#65]
### Rule

MEQP Version 4 is released under new repo which not merged in extdn-phpcs

### Reason

A lot of Magento 2 specific rules are added with severity 10  which should be added

### Implementation

Merge https://github.com/magento/magento-coding-standard/

**Comment by jissereitsma** [comment]
Hi @milindsingh1 thanks for your comment. It was actually and partially the work in this repo that led to the improved Magento Coding Standard, but we were aiming for this ExtDN standard to be removed in favor of the official Magento Coding Standard. Currently, all outstanding issues in this repo will be reviewed and either removed or turned into a PR for the official Magento Coding Standard. Once that is done, this repo will be removed as a whole.
