### ISSUE TITLE
Rule: No Object Manager in PHTML templates

### ISSUE THREAD

**Issue by jissereitsma** [extdn/extdn-phpcs#7]
The Object Manager should not appear in PHTML templates.

**Comment by avstudnitz** [comment]
Yes, that should be mandatory.

**Comment by fooman** [comment]
Thanks @larsroettig 

@navarr yeap I think would be good to have a separate discussion on this - feel free to open up a new issue for it. My gut feeling is that it will tie in with using block view models (2.2+).
